"use client";

import type { ReactNode } from "react";
import { GeneratedAvatar } from "./generated-avatar";
import { Icon } from "./icon";
import { LocationLookupFields } from "./location-lookup-fields";

const purchaseTypeOptions = ["Cash", "Conventional financing", "Other"];
const seekingPropertyTypeOptions = ["House", "Condo", "Townhouse", "Manufactured", "Land"];

const bedroomsOptions = [
  { label: "Any bedrooms", value: "" },
  { label: "1+ bedrooms", value: "1" },
  { label: "2+ bedrooms", value: "2" },
  { label: "3+ bedrooms", value: "3" },
  { label: "4+ bedrooms", value: "4" },
  { label: "5+ bedrooms", value: "5" },
];

const bathroomsOptions = [
  { label: "Any bathrooms", value: "" },
  { label: "1+ bathrooms", value: "1" },
  { label: "2+ bathrooms", value: "2" },
  { label: "3+ bathrooms", value: "3" },
  { label: "4+ bathrooms", value: "4" },
];

const yearBuiltOptions = [
  { label: "Any year", value: "" },
  { label: "1950 or newer", value: "1950" },
  { label: "1970 or newer", value: "1970" },
  { label: "1990 or newer", value: "1990" },
  { label: "2010 or newer", value: "2010" },
];

const conditionOptions = ["Any condition", "Move-in ready", "Mild fixer", "Fixer"];

const amenityOptions = ["Pool", "Parking", "ADU", "Yard", "Garage"];

type CriteriaForWizard = {
  bedroomsMin?: number;
  bathroomsMin?: number;
  squareFeetMin?: number;
  squareFeetMax?: number;
  lotSizeMin?: number;
  lotSizeMax?: number;
  yearBuiltMin?: number;
  condition?: string;
  features?: string[];
};

type BuyerForWizard = {
  avatarVariant?: string | null;
  id: string;
  name: string;
  type: string;
  purpose: string;
  location: string;
  city: string;
  neighborhood?: string;
  postalCode?: string;
  state: string;
  lat: string | number;
  lng: string | number;
  budgetMin: number;
  budgetMax: number;
  downPaymentMin: number;
  downPaymentMax: number;
  bio: string;
  criteriaDetails?: CriteriaForWizard[];
  serviceAreaSlugs?: string[];
  userId?: string;
};

export function BuyerProfileWizard({
  action,
  buyer,
  marketSlug,
  previousAvatarAction,
  regenerateAliasAction,
  shuffleAction,
}: {
  action: (formData: FormData) => Promise<void>;
  buyer: BuyerForWizard;
  marketSlug: string;
  previousAvatarAction: (formData: FormData) => Promise<void>;
  regenerateAliasAction: (formData: FormData) => Promise<void>;
  shuffleAction: (formData: FormData) => Promise<void>;
}) {
  const criteria = buyer.criteriaDetails?.[0];
  const selectedAmenities = new Set(
    (criteria?.features ?? [])
      .map((feature) => feature.trim().toLowerCase())
      .filter((feature) => amenityOptions.some((amenity) => amenity.toLowerCase() === feature)),
  );
  const avatarSeed = buyer.userId || buyer.id || buyer.name;
  const selectedPurchaseType = purchaseTypeOptions.includes(buyer.type) ? buyer.type : "Conventional financing";
  const selectedSeekingPropertyType = seekingPropertyTypeOptions.includes(buyer.purpose) ? buyer.purpose : "House";

  return (
    <form action={action} className="buyer-profile-form profile-reference-form">
      <ProfileFormSection eyebrow="Buyer info" title="Profile">
        <div className="form-grid">
          <div className="field">
            <label>Public buyer alias</label>
            <div className="buyer-alias-control">
              <span className="buyer-alias-value">{buyer.name}</span>
              <button className="button secondary sm" formAction={regenerateAliasAction} formNoValidate type="submit">
                Regenerate alias
              </button>
            </div>
            <span className="field-hint">Generated by Liber to protect your privacy.</span>
          </div>
          <div className="field buyer-generated-avatar-field">
            <label>Avatar</label>
            <div className="buyer-generated-avatar-control">
              <GeneratedAvatar
                alt="Generated buyer avatar"
                seed={avatarSeed}
                size="lg"
                variant={buyer.avatarVariant}
              />
              <button
                aria-label="Previous avatar"
                className="button secondary sm avatar-arrow-button"
                formAction={previousAvatarAction}
                formNoValidate
                title="Previous avatar"
                type="submit"
              >
                <Icon name="arrow-left" size={14} />
              </button>
              <button className="button secondary sm" formAction={shuffleAction} formNoValidate type="submit">
                Shuffle avatar
              </button>
            </div>
          </div>
          <div className="field">
            <label htmlFor="buyerType">Purchase type</label>
            <select id="buyerType" name="buyerType" defaultValue={selectedPurchaseType}>
              {purchaseTypeOptions.map((option) => (
                <option key={option} value={option}>{option}</option>
              ))}
            </select>
          </div>
          <div className="field">
            <label htmlFor="purpose">Seeking property type</label>
            <select id="purpose" name="buyingPurpose" defaultValue={selectedSeekingPropertyType}>
              {seekingPropertyTypeOptions.map((option) => (
                <option key={option} value={option}>{option}</option>
              ))}
            </select>
          </div>
          <div className="field full">
            <span className="field-hint">
              Sellers will not see your legal name, photo, phone number, or uploaded documents.
            </span>
          </div>
        </div>
      </ProfileFormSection>

      <ProfileFormSection eyebrow="Property criteria" title="Criteria">
        <div className="form-grid">
          <NumberRangeField
            defaultMax={String(buyer.budgetMax || "1000000")}
            defaultMin={String(buyer.budgetMin || "")}
            label="Budget range"
            max={3_000_000}
            maxId="budgetMax"
            maxName="budgetMax"
            min={0}
            minId="budgetMin"
            minName="budgetMin"
            prefix="$"
            step="any"
          />
          <NumberRangeField
            defaultMax={String(buyer.downPaymentMax || "200000")}
            defaultMin={String(buyer.downPaymentMin || "")}
            label="Down payment range"
            max={1_000_000}
            maxId="downPaymentMax"
            maxName="downPaymentMax"
            min={0}
            minId="downPaymentMin"
            minName="downPaymentMin"
            prefix="$"
            step="any"
          />
          <div className="field">
            <label htmlFor="bedroomsMin">Bedrooms</label>
            <select id="bedroomsMin" name="bedroomsMin" defaultValue={String(criteria?.bedroomsMin || "")}>
              {bedroomsOptions.map((option) => (
                <option key={option.label} value={option.value}>{option.label}</option>
              ))}
            </select>
          </div>
          <div className="field">
            <label htmlFor="bathroomsMin">Bathrooms</label>
            <select id="bathroomsMin" name="bathroomsMin" defaultValue={String(criteria?.bathroomsMin || "")}>
              {bathroomsOptions.map((option) => (
                <option key={option.label} value={option.value}>{option.label}</option>
              ))}
            </select>
          </div>
          <div className="field">
            <label htmlFor="yearBuiltMin">Year built</label>
            <select id="yearBuiltMin" name="yearBuiltMin" defaultValue={String(criteria?.yearBuiltMin || "")}>
              {yearBuiltOptions.map((option) => (
                <option key={option.label} value={option.value}>{option.label}</option>
              ))}
            </select>
          </div>
          <div className="field full">
            <label>Amenities you need</label>
            <div className="pill-row buyer-amenity-row">
              {amenityOptions.map((amenity) => (
                <label className="checkbox-container" key={amenity}>
                  <input
                    defaultChecked={selectedAmenities.has(amenity.toLowerCase())}
                    name="features"
                    type="checkbox"
                    value={amenity}
                  />
                  <span className="checkmark" />
                  {amenity}
                </label>
              ))}
            </div>
          </div>
        </div>
      </ProfileFormSection>

      <ProfileFormSection eyebrow="Size" title="Size">
        <div className="form-grid">
          <NumberRangeField
            defaultMax={String(criteria?.squareFeetMax || "")}
            defaultMin={String(criteria?.squareFeetMin || "")}
            label="Square feet"
            max={6_000}
            maxId="squareFeetMax"
            maxName="squareFeetMax"
            min={0}
            minId="squareFeetMin"
            minName="squareFeetMin"
            step={1}
            suffix="sqft"
          />
          <NumberRangeField
            defaultMax={String(criteria?.lotSizeMax || "")}
            defaultMin={String(criteria?.lotSizeMin || "")}
            label="Lot size"
            max={20_000}
            maxId="lotSizeMax"
            maxName="lotSizeMax"
            min={0}
            minId="lotSizeMin"
            minName="lotSizeMin"
            step={1}
            suffix="sqft"
          />
        </div>
      </ProfileFormSection>

      <ProfileFormSection eyebrow="Details" title="Details">
        <div className="form-grid">
          <div className="field full">
            <label htmlFor="condition">Condition</label>
            <select id="condition" name="condition" defaultValue={criteria?.condition ?? ""}>
              {conditionOptions.map((option) => (
                <option key={option} value={option === "Any condition" ? "" : option}>{option}</option>
              ))}
            </select>
          </div>
          <div className="field full">
            <label htmlFor="bio">Bio</label>
            <textarea
              id="bio"
              name="bio"
              defaultValue={buyer.bio}
              placeholder="Looking to simplify life in a quiet, comfortable home with low maintenance and good access to family."
            />
          </div>
        </div>
      </ProfileFormSection>

      <ProfileFormSection eyebrow="Location" title="Location">
        <div className="form-grid">
          <LocationLookupFields
            defaultLocation={buyer.location}
            defaultServiceAreaSlug={buyer.serviceAreaSlugs?.[0] ?? ""}
            inputId="desiredServiceAreaSearch"
            label="Search city, neighborhood, or ZIP"
            marketSlug={marketSlug}
          />
        </div>
      </ProfileFormSection>

      <div className="buyer-profile-submit">
        <button className="button primary" type="submit">
          Submit Profile
        </button>
      </div>
    </form>
  );
}

function ProfileFormSection({
  children,
  eyebrow,
  title,
}: {
  children: ReactNode;
  eyebrow: string;
  title: string;
}) {
  return (
    <section className="buyer-form-section">
      <div className="buyer-form-section-label">
        <h2>{title}</h2>
        <p>{eyebrow}</p>
      </div>
      <div className="buyer-form-fields">{children}</div>
    </section>
  );
}

type NumberRangeFieldProps = {
  defaultMax: string;
  defaultMin: string;
  label: string;
  max: number;
  maxId: string;
  maxName: string;
  min: number;
  minId: string;
  minName: string;
  prefix?: string;
  step: number | "any";
  suffix?: string;
};

function NumberRangeField({
  defaultMax,
  defaultMin,
  label,
  max,
  maxId,
  maxName,
  min,
  minId,
  minName,
  prefix,
  step,
  suffix,
}: NumberRangeFieldProps) {
  return (
    <div className="field full range-field buyer-range-field">
      <label>{label}</label>
      <div className="range-input-pair">
        <label className="range-number-box" htmlFor={minId}>
          <span>Min</span>
          <span className="range-number-wrap">
            {prefix ? <span className="range-prefix" aria-hidden="true">{prefix}</span> : null}
            <input
              className={`range-number-input ${prefix ? "has-prefix" : ""} ${suffix ? "has-suffix" : ""}`}
              defaultValue={defaultMin}
              id={minId}
              inputMode="numeric"
              max={max}
              min={min}
              name={minName}
              placeholder="No min"
              step={step}
              type="number"
            />
            {suffix ? <span className="range-suffix" aria-hidden="true">{suffix}</span> : null}
          </span>
        </label>
        <span className="range-to" aria-hidden="true">to</span>
        <label className="range-number-box" htmlFor={maxId}>
          <span>Max</span>
          <span className="range-number-wrap">
            {prefix ? <span className="range-prefix" aria-hidden="true">{prefix}</span> : null}
            <input
              className={`range-number-input ${prefix ? "has-prefix" : ""} ${suffix ? "has-suffix" : ""}`}
              defaultValue={defaultMax}
              id={maxId}
              inputMode="numeric"
              max={max}
              min={min}
              name={maxName}
              placeholder="No max"
              step={step}
              type="number"
            />
            {suffix ? <span className="range-suffix" aria-hidden="true">{suffix}</span> : null}
          </span>
        </label>
      </div>
    </div>
  );
}
