"use client";

import {
  startTransition,
  useActionState,
  useEffect,
  useRef,
  type FormEvent,
  type ReactNode,
} from "react";
import type { BuyerProfileFormState } from "../lib/buyer-profile-form";
import { GeneratedAvatar } from "./generated-avatar";
import { LocationLookupFields } from "./location-lookup-fields";
import { PropertyTypePicker } from "./property-type-picker";

const purchaseTypeOptions = ["Cash", "Conventional financing", "Other"];
const seekingPropertyTypeOptions = ["House", "Condo", "Townhouse", "Manufactured", "Land"];

const bedroomsOptions = [
  { label: "Any bedrooms", value: "" },
  { label: "1+ bedrooms", value: "1" },
  { label: "2+ bedrooms", value: "2" },
  { label: "3+ bedrooms", value: "3" },
  { label: "4+ bedrooms", value: "4" },
  { label: "5+ bedrooms", value: "5" },
];

const bathroomsOptions = [
  { label: "Any bathrooms", value: "" },
  { label: "1+ bathrooms", value: "1" },
  { label: "2+ bathrooms", value: "2" },
  { label: "3+ bathrooms", value: "3" },
  { label: "4+ bathrooms", value: "4" },
];

const yearBuiltOptions = [
  { label: "Any year", value: "" },
  { label: "1950 or newer", value: "1950" },
  { label: "1970 or newer", value: "1970" },
  { label: "1990 or newer", value: "1990" },
  { label: "2010 or newer", value: "2010" },
];

const conditionOptions = ["Any condition", "Move-in ready", "Mild fixer", "Fixer"];

const amenityOptions = ["Pool", "Parking", "ADU", "Yard", "Garage"];

type CriteriaForWizard = {
  bedroomsMin?: number;
  bathroomsMin?: number;
  squareFeetMin?: number;
  squareFeetMax?: number;
  lotSizeMin?: number;
  lotSizeMax?: number;
  yearBuiltMin?: number;
  condition?: string;
  features?: string[];
};

type BuyerForWizard = {
  avatarVariant?: string | null;
  id: string;
  name: string;
  type: string;
  purpose: string;
  location: string;
  city: string;
  neighborhood?: string;
  postalCode?: string;
  state: string;
  lat: string | number;
  lng: string | number;
  budgetMin: number;
  budgetMax: number;
  downPaymentMin: number;
  downPaymentMax: number;
  bio: string;
  criteriaDetails?: CriteriaForWizard[];
  serviceAreaSlugs?: string[];
  userId?: string;
};

export function BuyerProfileWizard({
  action,
  buyer,
  isPublished,
  marketSlug,
}: {
  action: (state: BuyerProfileFormState, formData: FormData) => Promise<BuyerProfileFormState>;
  buyer: BuyerForWizard;
  isPublished: boolean;
  marketSlug: string;
}) {
  const [state, formAction, isPending] = useActionState(action, { message: "" });
  const errorRef = useRef<HTMLDivElement>(null);
  const criteria = buyer.criteriaDetails?.[0];
  const selectedAmenities = new Set(
    (criteria?.features ?? [])
      .map((feature) => feature.trim().toLowerCase())
      .filter((feature) => amenityOptions.some((amenity) => amenity.toLowerCase() === feature)),
  );
  const avatarSeed = buyer.userId || buyer.id || buyer.name;
  const selectedPurchaseType = purchaseTypeOptions.includes(buyer.type) ? buyer.type : "Conventional financing";
  const selectedSeekingPropertyType = seekingPropertyTypeOptions.includes(buyer.purpose) ? buyer.purpose : "House";

  useEffect(() => {
    if (!state.message || !errorRef.current) return;
    errorRef.current.focus();
    errorRef.current.scrollIntoView({
      behavior: window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "auto" : "smooth",
      block: "center",
    });
  }, [state.message]);

  function submitProfile(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const formData = new FormData(event.currentTarget);
    startTransition(() => formAction(formData));
  }

  return (
    <form aria-busy={isPending} className="buyer-profile-form profile-reference-form" onSubmit={submitProfile}>
      <input name="profileIntent" type="hidden" value={isPublished ? "save" : "publish"} />
      <ProfileFormSection eyebrow="Private by default" title="Buyer identity">
        <div className="form-grid">
          <div className="field">
            <span className="field-label">Public alias</span>
            <div className="buyer-alias-control">
              <span className="buyer-alias-value">{buyer.name}</span>
            </div>
            <span className="field-hint">Generated by Liber to protect your privacy.</span>
          </div>
          <div className="field buyer-generated-avatar-field">
            <span className="field-label">Generated avatar</span>
            <div className="buyer-generated-avatar-control">
              <GeneratedAvatar
                alt="Generated buyer avatar"
                seed={avatarSeed}
                size="lg"
                variant={buyer.avatarVariant}
              />
              <span className="field-hint">You can change this after saving your profile.</span>
            </div>
          </div>
          <div className="field full">
            <span className="field-hint">
              Sellers will not see your legal name, photo, phone number, or uploaded documents.
            </span>
          </div>
        </div>
      </ProfileFormSection>

      <ProfileFormSection eyebrow="Core details" title="Budget & basics">
        <div className="form-grid">
          <div className="field">
            <label htmlFor="buyerType">Purchase type</label>
            <select id="buyerType" name="buyerType" defaultValue={selectedPurchaseType} required>
              {purchaseTypeOptions.map((option) => (
                <option key={option} value={option}>{option}</option>
              ))}
            </select>
          </div>
          <PropertyTypePicker
            defaultValue={selectedSeekingPropertyType}
            legend="Seeking property type"
            name="buyingPurpose"
            required
            valueMode="label"
          />
          <NumberRangeField
            defaultMax={String(buyer.budgetMax || "")}
            defaultMin={String(buyer.budgetMin || "")}
            label="Budget range (required)"
            maxId="budgetMax"
            maxName="budgetMax"
            min={0}
            minId="budgetMin"
            minName="budgetMin"
            prefix="$"
            required
            step="any"
          />
          <NumberRangeField
            defaultMax={String(buyer.downPaymentMax || "")}
            defaultMin={String(buyer.downPaymentMin || "")}
            label="Down payment range"
            maxId="downPaymentMax"
            maxName="downPaymentMax"
            min={0}
            minId="downPaymentMin"
            minName="downPaymentMin"
            prefix="$"
            step="any"
          />
          <div className="field">
            <label htmlFor="bedroomsMin">Bedrooms</label>
            <select id="bedroomsMin" name="bedroomsMin" defaultValue={String(criteria?.bedroomsMin || "")}>
              {bedroomsOptions.map((option) => (
                <option key={option.label} value={option.value}>{option.label}</option>
              ))}
            </select>
          </div>
          <div className="field">
            <label htmlFor="bathroomsMin">Bathrooms</label>
            <select id="bathroomsMin" name="bathroomsMin" defaultValue={String(criteria?.bathroomsMin || "")}>
              {bathroomsOptions.map((option) => (
                <option key={option.label} value={option.value}>{option.label}</option>
              ))}
            </select>
          </div>
        </div>
      </ProfileFormSection>

      <ProfileFormSection eyebrow="Optional" title="Home & lot size">
        <div className="form-grid">
          <NumberRangeField
            defaultMax={String(criteria?.squareFeetMax || "")}
            defaultMin={String(criteria?.squareFeetMin || "")}
            label="Square feet"
            maxId="squareFeetMax"
            maxName="squareFeetMax"
            min={0}
            minId="squareFeetMin"
            minName="squareFeetMin"
            step={1}
            suffix="sqft"
          />
          <NumberRangeField
            defaultMax={String(criteria?.lotSizeMax || "")}
            defaultMin={String(criteria?.lotSizeMin || "")}
            label="Lot size"
            maxId="lotSizeMax"
            maxName="lotSizeMax"
            min={0}
            minId="lotSizeMin"
            minName="lotSizeMin"
            step={1}
            suffix="sqft"
          />
          <div className="field full">
            <label htmlFor="yearBuiltMin">Year built</label>
            <select id="yearBuiltMin" name="yearBuiltMin" defaultValue={String(criteria?.yearBuiltMin || "")}>
              {yearBuiltOptions.map((option) => (
                <option key={option.label} value={option.value}>{option.label}</option>
              ))}
            </select>
          </div>
        </div>
      </ProfileFormSection>

      <ProfileFormSection eyebrow="Optional" title="Preferences">
        <div className="form-grid">
          <div className="field full">
            <label htmlFor="condition">Condition</label>
            <select id="condition" name="condition" defaultValue={criteria?.condition ?? ""}>
              {conditionOptions.map((option) => (
                <option key={option} value={option === "Any condition" ? "" : option}>{option}</option>
              ))}
            </select>
          </div>
          <fieldset className="field full buyer-amenities-field">
            <legend>Amenities you need</legend>
            <div className="pill-row buyer-amenity-row">
              {amenityOptions.map((amenity) => (
                <label className="checkbox-container" key={amenity}>
                  <input
                    defaultChecked={selectedAmenities.has(amenity.toLowerCase())}
                    name="features"
                    type="checkbox"
                    value={amenity}
                  />
                  <span className="checkmark" />
                  {amenity}
                </label>
              ))}
            </div>
          </fieldset>
          <div className="field full">
            <label htmlFor="bio">Note to matching sellers</label>
            <textarea
              id="bio"
              name="bio"
              defaultValue={buyer.bio}
              placeholder="Looking to simplify life in a quiet, comfortable home with low maintenance and good access to family."
            />
          </div>
        </div>
      </ProfileFormSection>

      <ProfileFormSection eyebrow="Required" title="Target area">
        <div className="form-grid">
          <LocationLookupFields
            defaultLocation={buyer.location}
            defaultServiceAreaSlug={buyer.serviceAreaSlugs?.[0] ?? ""}
            inputId="desiredServiceAreaSearch"
            label="Search city, neighborhood, or ZIP"
            marketSlug={marketSlug}
          />
        </div>
      </ProfileFormSection>

      {state.message ? (
        <div
          className="auth-alert warning buyer-profile-form-error"
          ref={errorRef}
          role="alert"
          tabIndex={-1}
        >
          <strong>Check your profile</strong>
          <span>{state.message}</span>
        </div>
      ) : null}

      <div className="buyer-profile-submit">
        <button className="button primary" disabled={isPending} type="submit">
          {isPending
            ? isPublished ? "Saving changes..." : "Publishing profile..."
            : isPublished ? "Save changes" : "Publish buyer profile"}
        </button>
      </div>
    </form>
  );
}

function ProfileFormSection({
  children,
  eyebrow,
  title,
}: {
  children: ReactNode;
  eyebrow: string;
  title: string;
}) {
  return (
    <section className="buyer-form-section">
      <div className="buyer-form-section-label">
        <h2>{title}</h2>
        <p>{eyebrow}</p>
      </div>
      <div className="buyer-form-fields">{children}</div>
    </section>
  );
}

type NumberRangeFieldProps = {
  defaultMax: string;
  defaultMin: string;
  label: string;
  maxId: string;
  maxName: string;
  min: number;
  minId: string;
  minName: string;
  prefix?: string;
  required?: boolean;
  step: number | "any";
  suffix?: string;
};

function NumberRangeField({
  defaultMax,
  defaultMin,
  label,
  maxId,
  maxName,
  min,
  minId,
  minName,
  prefix,
  required = false,
  step,
  suffix,
}: NumberRangeFieldProps) {
  return (
    <fieldset className="field full range-field buyer-range-field">
      <legend>{label}</legend>
      <div className="range-input-pair">
        <label className="range-number-box" htmlFor={minId}>
          <span>Min</span>
          <span className="range-number-wrap">
            {prefix ? <span className="range-prefix" aria-hidden="true">{prefix}</span> : null}
            <input
              className={`range-number-input ${prefix ? "has-prefix" : ""} ${suffix ? "has-suffix" : ""}`}
              defaultValue={defaultMin}
              id={minId}
              inputMode="numeric"
              min={min}
              name={minName}
              placeholder="No min"
              required={required}
              step={step}
              type="number"
            />
            {suffix ? <span className="range-suffix" aria-hidden="true">{suffix}</span> : null}
          </span>
        </label>
        <span className="range-to" aria-hidden="true">to</span>
        <label className="range-number-box" htmlFor={maxId}>
          <span>Max</span>
          <span className="range-number-wrap">
            {prefix ? <span className="range-prefix" aria-hidden="true">{prefix}</span> : null}
            <input
              className={`range-number-input ${prefix ? "has-prefix" : ""} ${suffix ? "has-suffix" : ""}`}
              defaultValue={defaultMax}
              id={maxId}
              inputMode="numeric"
              min={min}
              name={maxName}
              placeholder="No max"
              required={required}
              step={step}
              type="number"
            />
            {suffix ? <span className="range-suffix" aria-hidden="true">{suffix}</span> : null}
          </span>
        </label>
      </div>
    </fieldset>
  );
}
